### ISSUE TITLE
Add a remittance recipient registration

### ISSUE THREAD

**Issue by UZAMARU** [lisknonanika/lisk-simple-wallet#5]

**Comment by lisknonanika** [comment]
- [x] Add "recipient screen".
- [x] Make it possible to register recipients on "send screen".
- [x] Make it possible to call "recipient screen" from "send screen".
- [x] Make it possible to call "recipient screen" from "account info screen".

**Comment by lisknonanika** [comment]
Add "recipient screen".
![5](https://user-images.githubusercontent.com/44485074/135031342-454f25a6-2678-44e1-8e03-f84557fe864e.PNG)
![6](https://user-images.githubusercontent.com/44485074/135031784-e979b330-a20e-4db0-a019-11857e92b1cd.PNG)

Make it possible to register recipients on "send screen".
![image](https://user-images.githubusercontent.com/44485074/135031405-c46f34ac-7118-47db-a5de-1f5f6c5da84b.png)

Make it possible to call "recipient screen" from "send screen".
![image](https://user-images.githubusercontent.com/44485074/135031481-afd62c10-e737-4d7b-9f4f-34a324916f40.png)

Make it possible to call "recipient screen" from "account info screen".
![image](https://user-images.githubusercontent.com/44485074/135031569-85b6f343-3b7e-4deb-85be-b2f35ee5ed28.png)

* bookmark is not exists
![image](https://user-images.githubusercontent.com/44485074/135031693-d6236b10-ba8b-4ca4-abff-6e3e60bdad0b.png)
